sonar.projectKey=uth-confms
sonar.projectName=KCPM Conference System
sonar.projectVersion=1.0

# KẾT NỐI SERVER
sonar.host.url=http://127.0.0.1:9000
sonar.login=sqp_853662be9a16d2c0a4f5323e8545cc49f0eab7b4

# Đường dẫn tới thư mục chứa source code
sonar.sources=apps

# Loại bỏ các file test, thư mục rác khỏi việc phân tích source code chính
sonar.exclusions=**/*.spec.ts,**/node_modules/**,dist/**,coverage/**,**/*.module.ts

# Đường dẫn cài đặt gốc của bộ test
sonar.tests=apps
sonar.test.inclusions=**/*.spec.ts

# Nơi SonarQube đọc kết quả độ phủ 80% từ Jest
sonar.javascript.lcov.reportPaths=coverage/lcov.info
