sonar.projectKey=uth-confms
sonar.projectName=KCPM Conference System
sonar.projectVersion=1.0

# ── KẾT NỐI SERVER LOCAL ──────────────────────────────────────────────────────
sonar.host.url=http://127.0.0.1:9000
sonar.login=sqp_853662be9a16d2c0a4f5323e8545cc49f0eab7b4

# ── SOURCE CODE ───────────────────────────────────────────────────────────────
sonar.sources=apps
sonar.exclusions=**/*.spec.ts,**/node_modules/**,dist/**,coverage/**,**/*.module.ts

# ── TEST & COVERAGE ───────────────────────────────────────────────────────────
sonar.tests=apps
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
